apiVersion: v1
kind: Service
metadata:
  name: ecommerce_web
  labels:
    app: ecommerce_web
spec:
  selector:
    app: ecommerce_web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce_web
  labels:
    app: ecommerce_web
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce_web
      version: v1
  template:
    metadata:
      labels:
        app: ecommerce_web
        version: v1
    spec:
      containers:
        - name: ecommerce_web
          image: ghcr.io/sony-nurdianto/ecommerce_web:v0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            privileged: false
      imagePullSecrets:
        - name: github-secrets
   
