apiVersion: v1
kind: Secret
metadata:
  name: github-secrets
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJZbUZ6WlRZMElIc2ljMjl1ZVMxdWRYSmthV0Z1ZEc4aU9pQWlaMmh3WDNsRWRXbDBSakV6WVVwcmNUQnZVbk40TTNWNk5YQkJZbTQxUm01aU16STBSSFF5YWlKOUNnPT0iIAogICAgfQogIH0KfQo=
